# Generated by Django 5.1.15 on 2026-04-11 21:50

import typeclasses.objects
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultObject",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.objectdb",),
        ),
        migrations.CreateModel(
            name="DefaultCharacter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultExit",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="DefaultRoom",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("objects.defaultobject",),
        ),
        migrations.CreateModel(
            name="Object",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(typeclasses.objects.ObjectParent, "objects.defaultobject"),
        ),
        migrations.CreateModel(
            name="Character",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(typeclasses.objects.ObjectParent, "objects.defaultcharacter"),
        ),
    ]
