# Generated by Django 5.1.15 on 2026-04-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0016_scriptbase_alter_scriptdb_id_defaultscript_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptBase",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.scriptdb",),
        ),
        migrations.CreateModel(
            name="DefaultScript",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.scriptbase",),
        ),
        migrations.CreateModel(
            name="BotStarter",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
        migrations.CreateModel(
            name="DbPrototype",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
        migrations.CreateModel(
            name="DoNothing",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
        migrations.CreateModel(
            name="Store",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
        migrations.CreateModel(
            name="TimeScript",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("scripts.defaultscript",),
        ),
    ]
