# Generated by Django 5.1.15 on 2026-04-11 21:50

import evennia.accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_defaultaccount_alter_accountdb_id_account_bot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultAccount",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.accountdb",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.defaultaccount",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.defaultaccount",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="DefaultGuest",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.defaultaccount",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="DiscordBot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.bot",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="GrapevineBot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.bot",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="IRCBot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.bot",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="RSSBot",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.bot",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.defaultguest",),
            managers=[
                ("objects", evennia.accounts.manager.AccountManager()),
            ],
        ),
    ]
